const config = {
  MAIN: {
    PORT: 8081,
    CLIENT_PORT: 3000,
    PATH_DATA_FILES: '',
    TIMEOUT_BETWEEN_EPOCHS_MS: 500,
    NUMBER_TRAINING_ITERATIONS: 10,
    RECONNECTION_DELAY: 300,
    RECONNECTION_DELAY_MAX: 300,
  },
};

module.exports = config;
